<?php

use Illuminate\Database\Seeder;

class ConfigurationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('configurations')->delete();
        
        \DB::table('configurations')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'TITLE',
                'display_name' => 'Title',
                'config_type' => 'DD',
                'options' => NULL,
                'default_value' => NULL,
                'value' => 'Mr',
                'options_array' => '"{\\"Mr\\":\\"Mr\\",\\"Mrs\\":\\"Mrs\\",\\"Ms\\":\\"Ms\\",\\"Dr\\":\\"Dr\\",\\"Prof\\":\\"Prof\\",\\"Master\\":\\"Master\\",\\"Reverent\\":\\"Reverent\\"}"',
                'category_id' => 1,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-09-27 07:00:11',
                'updated_at' => '2019-11-08 08:07:34',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'DISCOUNT_TYPE',
                'display_name' => 'Discount Type',
                'config_type' => 'DD',
                'options' => NULL,
                'default_value' => NULL,
                'value' => 'P',
            'options_array' => '"{\\"A\\":\\"Amount\\",\\"P\\":\\"Percentage (%)\\"}"',
                'category_id' => 1,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-09-27 07:11:09',
                'updated_at' => '2019-10-10 04:11:35',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'INQUIRY_STATUS',
                'display_name' => 'Inquiry status',
                'config_type' => 'DD',
                'options' => NULL,
                'default_value' => NULL,
                'value' => 'P',
                'options_array' => '"{\\"P\\":\\"Pending\\",\\"O\\":\\"Processing\\",\\"C\\":\\"Completed\\",\\"R\\":\\"Rejected\\"}"',
                'category_id' => 1,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-10-01 07:10:14',
                'updated_at' => '2019-10-30 10:06:51',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'INQUIRY_PRIORITY',
                'display_name' => 'Inquiry Priority',
                'config_type' => 'DD',
                'options' => NULL,
                'default_value' => NULL,
                'value' => 'N',
                'options_array' => '"{\\"L\\":\\"Low\\",\\"N\\":\\"Normal\\",\\"H\\":\\"High\\",\\"U\\":\\"Urgent\\"}"',
                'category_id' => 2,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-10-01 07:18:17',
                'updated_at' => '2019-10-30 10:04:28',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'DEFAULT_CURRENCY',
                'display_name' => 'Default Currency',
                'config_type' => 'TX',
                'options' => NULL,
                'default_value' => NULL,
                'value' => 'Rs.',
                'options_array' => NULL,
                'category_id' => 1,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-10-11 09:42:16',
                'updated_at' => '2019-10-11 09:42:16',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'ADDRESS_USER_TYPE',
                'display_name' => 'Address user type',
                'config_type' => 'DD',
                'options' => NULL,
                'default_value' => NULL,
                'value' => '',
                'options_array' => '"{\\"supplier\\":\\"S\\",\\"customer\\":\\"C\\"}"',
                'category_id' => 2,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-10-17 04:03:46',
                'updated_at' => '2019-10-17 04:03:46',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'VAT_PERCENTAGE',
                'display_name' => 'VAT_PERCENTAGE',
                'config_type' => 'TX',
                'options' => NULL,
                'default_value' => NULL,
                'value' => '15',
                'options_array' => NULL,
                'category_id' => 1,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-10-21 10:54:59',
                'updated_at' => '2019-10-21 10:54:59',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'NBT_PERCENTAGE',
                'display_name' => 'NBT_PERCENTAGE',
                'config_type' => 'TX',
                'options' => NULL,
                'default_value' => NULL,
                'value' => '2',
                'options_array' => NULL,
                'category_id' => 1,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-10-21 10:55:13',
                'updated_at' => '2019-10-21 10:55:13',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'MEDIA_TYPES',
                'display_name' => 'Media Types',
                'config_type' => 'DD',
                'options' => NULL,
                'default_value' => NULL,
                'value' => '',
                'options_array' => '"{\\"products_media\\":\\"products_media\\",\\"project_attachments\\":\\"project_attachments\\",\\"finance_attachments\\":\\"finance_attachments\\",\\"company_logo\\":\\"company_logo\\"}"',
                'category_id' => 2,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-10-27 02:56:52',
                'updated_at' => '2019-11-06 08:48:01',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'TRANSACTION_TYPES',
                'display_name' => 'Transaction Types',
                'config_type' => 'DD',
                'options' => NULL,
                'default_value' => NULL,
                'value' => '',
                'options_array' => '"{\\"stock_adjustment\\":\\"1\\",\\"sales_order\\":\\"2\\",\\"grn\\":\\"3\\",\\"purchase_returns\\":\\"4\\",\\"invoice_return\\":\\"5\\"}"',
                'category_id' => 2,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-10-30 17:49:32',
                'updated_at' => '2019-10-30 17:49:32',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'STOCK_TRANSACTION_TYPES',
                'display_name' => 'Stock Transaction Types',
                'config_type' => 'DD',
                'options' => NULL,
                'default_value' => NULL,
                'value' => '',
                'options_array' => '"{\\"stock_adjustment\\":\\"1\\",\\"sales_order\\":\\"2\\",\\"grn\\":\\"3\\",\\"purchase_returns\\":\\"4\\",\\"invoice_return\\":\\"5\\",\\"manual_update\\":\\"6\\",\\"production_consumed_product\\":\\"7\\",\\"production\\":\\"8\\"}"',
                'category_id' => 2,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-10-30 19:00:18',
                'updated_at' => '2020-05-07 00:04:06',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'TRANSMISSION_TYPES',
                'display_name' => 'Transmission Types',
                'config_type' => 'DD',
                'options' => NULL,
                'default_value' => NULL,
                'value' => '',
                'options_array' => '"{\\"M\\":\\"Manual\\",\\"A\\":\\"Automatic\\",\\"T\\":\\"Tiptronic\\",\\"O\\":\\"Other Transmission\\"}"',
                'category_id' => 4,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-11-05 22:56:52',
                'updated_at' => '2019-11-05 22:56:52',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'COMPANY_DETAILS',
                'display_name' => 'Company Details',
                'config_type' => 'DD',
                'options' => NULL,
                'default_value' => NULL,
                'value' => '',
                'options_array' => '"{\\"_token\\":\\"KIQmAvpP1uohgNcEozubP7uPsS0GidrBLmfsnQuH\\",\\"ref_id\\":\\"\\",\\"media_type\\":\\"company_logo\\",\\"media_ids\\":\\"\\",\\"company_name\\":\\"CMK Enterprises\\",\\"mobile\\":\\"0472237130\\",\\"telephone\\":\\"0472238130\\",\\"email\\":\\"sbscom@sltnet.lk\\",\\"website\\":\\"www.sbssrilanka.com\\",\\"street1\\":\\"No.479\\",\\"street2\\":\\"Debarawewa\\",\\"city\\":\\"Thissamaharama\\",\\"country\\":\\"LK\\"}"',
                'category_id' => 1,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 1,
                'updated_by' => 5,
                'deleted_at' => NULL,
                'created_at' => '2019-11-06 23:44:37',
                'updated_at' => '2020-06-01 14:06:18',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'CUSTOMER_TYPE',
                'display_name' => 'Customer Type',
                'config_type' => 'DD',
                'options' => NULL,
                'default_value' => NULL,
                'value' => 'C',
                'options_array' => '"{\\"C\\":\\"Customer\\",\\"B\\":\\"Company\\"}"',
                'category_id' => 1,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-11-28 12:58:12',
                'updated_at' => '2019-11-28 12:58:12',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'AOD_REASON',
                'display_name' => 'AOD Reason',
                'config_type' => 'DD',
                'options' => NULL,
                'default_value' => NULL,
                'value' => '',
                'options_array' => '"{\\"\\":\\"Select Reason\\",\\"st\\":\\"Stand by\\",\\"de\\":\\"Demonstration\\",\\"wc\\":\\"Warranty Claim\\",\\"do\\":\\"Donation\\"}"',
                'category_id' => 1,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-12-05 16:35:52',
                'updated_at' => '2019-12-05 16:35:52',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'RECURRING_TYPE',
                'display_name' => 'Recurring Type',
                'config_type' => 'DD',
                'options' => NULL,
                'default_value' => NULL,
                'value' => '',
                'options_array' => '"{\\"M\\":\\"Monthly\\",\\"Y\\":\\"Yearly\\",\\"\\":\\"Select Recurring Type\\"}"',
                'category_id' => 1,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-12-23 15:46:00',
                'updated_at' => '2019-12-24 10:28:55',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'SMS_CONFIG',
                'display_name' => 'Sms Config',
                'config_type' => 'DD',
                'options' => NULL,
                'default_value' => NULL,
                'value' => '',
                'options_array' => '"{\\"sms_api_key\\":\\"J7ZR-O1QW-N9WZ-P03T-AIL4\\",\\"sms_api_secret\\":\\"56Rv5ajLd3IIccja1OCV\\"}"',
                'category_id' => 5,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2020-01-01 10:28:05',
                'updated_at' => '2020-01-01 10:28:05',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'GRN_TAX',
                'display_name' => 'GRN TAX',
                'config_type' => 'TX',
                'options' => NULL,
                'default_value' => NULL,
                'value' => 'FALSE',
                'options_array' => NULL,
                'category_id' => 2,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2020-04-22 21:53:23',
                'updated_at' => '2020-04-22 21:53:23',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'INVOICE_TAX',
                'display_name' => 'Invoice Tax',
                'config_type' => 'TX',
                'options' => NULL,
                'default_value' => NULL,
                'value' => 'FALSE',
                'options_array' => NULL,
                'category_id' => 2,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2020-04-22 21:54:17',
                'updated_at' => '2020-04-22 21:54:17',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'ENABLE_INVOICE_RECURRING',
                'display_name' => 'Enable Invoice Recurring',
                'config_type' => 'TX',
                'options' => NULL,
                'default_value' => NULL,
                'value' => 'FALSE',
                'options_array' => NULL,
                'category_id' => 2,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2020-04-22 22:07:46',
                'updated_at' => '2020-04-22 22:07:46',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'INVOICE_COMPANY',
                'display_name' => 'Invoice Company',
                'config_type' => 'DD',
                'options' => NULL,
                'default_value' => NULL,
                'value' => '1',
                'options_array' => '"{\\"1\\":\\"Hasinidu Rice Mill\\",\\"2\\":\\"Hasinidu Steam Rice Mill\\"}"',
                'category_id' => 2,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 1,
                'updated_by' => 5,
                'deleted_at' => NULL,
                'created_at' => '2020-04-30 05:26:18',
                'updated_at' => '2020-06-01 13:55:29',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'PRODUCTION_COST_TYPE',
                'display_name' => 'Production Cost Type',
                'config_type' => 'DD',
                'options' => NULL,
                'default_value' => NULL,
                'value' => '',
                'options_array' => '"{\\"1\\":\\"Labor Cost\\",\\"2\\":\\"Machine Cost\\",\\"3\\":\\"Overhead Cost\\"}"',
                'category_id' => 1,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2020-04-30 19:24:12',
                'updated_at' => '2020-04-30 19:24:12',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'CUSTOMER_INVOICE_TYPES',
                'display_name' => 'Customer Invoice Types',
                'config_type' => 'DD',
                'options' => NULL,
                'default_value' => NULL,
                'value' => '10',
                'options_array' => '"{\\"10\\":\\"10\\",\\"35\\":\\"35\\"}"',
                'category_id' => 1,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 5,
                'updated_by' => 5,
                'deleted_at' => NULL,
                'created_at' => '2020-08-07 10:17:48',
                'updated_at' => '2020-08-07 10:18:55',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'BANKS_LIST',
                'display_name' => 'Banks List',
                'config_type' => 'DD',
                'options' => NULL,
                'default_value' => NULL,
                'value' => '',
                'options_array' => '"[\\"Amana Bank\\",\\"Bank of Ceylon\\",\\"Cargills Bank Ltd\\",\\"Commercial Bank of Ceylon PLC\\",\\"DFCC Bank PLC\\",\\"Hatton National Bank PLC\\",\\"National Development Bank PLC\\",\\"Nations Trust Bank PLC\\",\\"Pan Asia Banking Corporation PLC\\",\\"People\'s Bank\\",\\"Sampath Bank PLC\\",\\"Seylan Bank PLC\\",\\"Other Bank\\"]"',
                'category_id' => 1,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 5,
                'updated_by' => 5,
                'deleted_at' => NULL,
                'created_at' => '2020-08-18 05:45:37',
                'updated_at' => '2020-08-18 05:49:48',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'INVOICE_STATUS',
                'display_name' => 'Invoice Status',
                'config_type' => 'DD',
                'options' => NULL,
                'default_value' => NULL,
                'value' => '',
                'options_array' => '"{\\"O\\":\\"Order\\",\\"D\\":\\"Ready to Dispatch\\",\\"I\\":\\"Invoice\\",\\"Q\\":\\"Quick Sell\\"}"',
                'category_id' => 1,
                'status' => '1',
                'hidden' => '0',
                'created_by' => 5,
                'updated_by' => 5,
                'deleted_at' => NULL,
                'created_at' => '2020-08-29 18:28:13',
                'updated_at' => '2020-08-29 23:44:30',
            ),
        ));
        
        
    }
}