<?php

use Illuminate\Database\Seeder;

class CustomerTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('customer')->delete();
        
        \DB::table('customer')->insert(array (
            0 => 
            array (
                'id' => 9,
                'branch_id' => 2,
                'title' => 'Mr',
                'business_name' => 'Seylan Bank PLC',
                'customer_type' => 'V',
                'company_name' => '',
                'company_branch' => '',
                'fname' => 'Prasanna',
                'lname' => 'Perera',
                'nic' => '',
                'tax_no' => '',
                'passport_no' => NULL,
                'passport_expire_date' => NULL,
                'telephone' => '',
                'mobile' => '+94771252268',
                'email' => '',
                'dob' => NULL,
                'gender' => '',
                'website' => '',
                'remarks' => '',
                'outstanding_amount' => 0.0,
                'discount' => 0,
                'discount_type' => 'P',
                'status' => 'A',
                'user_account_id' => NULL,
                'user_id' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-11-16 10:46:12',
                'updated_at' => '2019-11-20 17:11:04',
            ),
            1 => 
            array (
                'id' => 8,
                'branch_id' => 1,
                'title' => 'Mr',
                'business_name' => 'SML',
                'customer_type' => 'V',
                'company_name' => NULL,
                'company_branch' => NULL,
                'fname' => 'Shamila',
                'lname' => 'Perera',
                'nic' => '',
                'tax_no' => '',
                'passport_no' => NULL,
                'passport_expire_date' => NULL,
                'telephone' => '',
                'mobile' => '+94711252236',
                'email' => '',
                'dob' => NULL,
                'gender' => 'm',
                'website' => '',
                'remarks' => '',
                'outstanding_amount' => 6200.0,
                'discount' => 0,
                'discount_type' => 'P',
                'status' => 'A',
                'user_account_id' => NULL,
                'user_id' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-11-16 00:02:03',
                'updated_at' => '2020-01-29 17:31:46',
            ),
            2 => 
            array (
                'id' => 7,
                'branch_id' => 2,
                'title' => 'Mr',
                'business_name' => 'PRAMIX',
                'customer_type' => 'V',
                'company_name' => NULL,
                'company_branch' => NULL,
                'fname' => 'Praveen',
                'lname' => 'Chameera',
                'nic' => '',
                'tax_no' => '110245',
                'passport_no' => NULL,
                'passport_expire_date' => NULL,
                'telephone' => '',
                'mobile' => '+94711252282',
                'email' => 'praveenchameera@gmail.com',
                'dob' => '1992-07-21',
                'gender' => 'm',
                'website' => 'http://www.pramixit.com',
                'remarks' => '',
                'outstanding_amount' => 1100.0,
                'discount' => 10,
                'discount_type' => 'P',
                'status' => 'A',
                'user_account_id' => NULL,
                'user_id' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-11-16 00:00:41',
                'updated_at' => '2019-12-13 08:52:11',
            ),
            3 => 
            array (
                'id' => 10,
                'branch_id' => 1,
                'title' => 'Mr',
                'business_name' => 'test',
                'customer_type' => 'C',
                'company_name' => NULL,
                'company_branch' => NULL,
                'fname' => 'Shamila',
                'lname' => 'Chathuranga',
                'nic' => '',
                'tax_no' => '',
                'passport_no' => NULL,
                'passport_expire_date' => NULL,
                'telephone' => '',
                'mobile' => '+94771252268',
                'email' => 'Shamila.e.c.f@gmail.com',
                'dob' => NULL,
                'gender' => '',
                'website' => '',
                'remarks' => '',
                'outstanding_amount' => 1400.0,
                'discount' => 0,
                'discount_type' => 'P',
                'status' => 'A',
                'user_account_id' => NULL,
                'user_id' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2020-01-29 10:34:17',
                'updated_at' => '2020-01-29 16:43:13',
            ),
            4 => 
            array (
                'id' => 11,
                'branch_id' => 1,
                'title' => 'Mr',
                'business_name' => 'test2',
                'customer_type' => 'C',
                'company_name' => NULL,
                'company_branch' => NULL,
                'fname' => 'Shamilaa',
                'lname' => 'Chathuranga',
                'nic' => '',
                'tax_no' => '',
                'passport_no' => NULL,
                'passport_expire_date' => NULL,
                'telephone' => '',
                'mobile' => '+94702700948',
                'email' => 'praveenchameera@gmail.com',
                'dob' => NULL,
                'gender' => '',
                'website' => '',
                'remarks' => '',
                'outstanding_amount' => 5000.0,
                'discount' => 0,
                'discount_type' => 'P',
                'status' => 'A',
                'user_account_id' => NULL,
                'user_id' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2020-01-29 10:36:25',
                'updated_at' => '2020-01-29 16:44:28',
            ),
            5 => 
            array (
                'id' => 12,
                'branch_id' => 2,
                'title' => 'Mr',
                'business_name' => 'test',
                'customer_type' => 'C',
                'company_name' => '',
                'company_branch' => '',
                'fname' => 'Shamila',
                'lname' => 'Chathuranga',
                'nic' => '',
                'tax_no' => '',
                'passport_no' => NULL,
                'passport_expire_date' => NULL,
                'telephone' => '',
                'mobile' => '+94702700948',
                'email' => 'Shamila.e.c.f@gmail.com',
                'dob' => NULL,
                'gender' => '',
                'website' => '',
                'remarks' => '',
                'outstanding_amount' => NULL,
                'discount' => 0,
                'discount_type' => 'P',
                'status' => 'A',
                'user_account_id' => NULL,
                'user_id' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2020-01-29 10:42:30',
                'updated_at' => '2020-01-29 10:42:30',
            ),
            6 => 
            array (
                'id' => 13,
                'branch_id' => 2,
                'title' => 'Mr',
                'business_name' => 'test2',
                'customer_type' => 'C',
                'company_name' => '',
                'company_branch' => '',
                'fname' => 'Shamila',
                'lname' => 'Chathuranga',
                'nic' => '',
                'tax_no' => '',
                'passport_no' => NULL,
                'passport_expire_date' => NULL,
                'telephone' => '',
                'mobile' => '+94702700947',
                'email' => 'praveenchameeraa@gmail.com',
                'dob' => NULL,
                'gender' => '',
                'website' => '',
                'remarks' => '',
                'outstanding_amount' => NULL,
                'discount' => 0,
                'discount_type' => 'P',
                'status' => 'A',
                'user_account_id' => NULL,
                'user_id' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2020-01-29 10:43:08',
                'updated_at' => '2020-01-29 10:43:08',
            ),
        ));
        
        
    }
}