<?php

use Illuminate\Database\Seeder;

class ProductCategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('product_categories')->delete();
        
        \DB::table('product_categories')->insert(array (
            0 => 
            array (
                'id' => 42,
                'branch_id' => 1,
                'category_code' => 'Z',
                'category_name' => 'ISUZU',
                'parent_id' => 0,
                'description' => 'PARTS FOR ISUZU',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:25:11',
                'updated_at' => '2020-11-14 11:25:11',
            ),
            1 => 
            array (
                'id' => 41,
                'branch_id' => 1,
                'category_code' => 'T09',
                'category_name' => 'TOYOTA FUEL FILTER',
                'parent_id' => 37,
                'description' => 'TOYOTA FUEL FILTERS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:24:07',
                'updated_at' => '2020-11-14 11:24:07',
            ),
            2 => 
            array (
                'id' => 40,
                'branch_id' => 1,
                'category_code' => 'A02',
                'category_name' => 'AMC HOOD LAMP',
                'parent_id' => 35,
                'description' => 'AMC HOOD LAMP',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:22:33',
                'updated_at' => '2020-11-14 11:22:33',
            ),
            3 => 
            array (
                'id' => 39,
                'branch_id' => 1,
                'category_code' => 'A01',
                'category_name' => 'AMC REAR LAMPS',
                'parent_id' => 35,
                'description' => 'AMC REAR LAMPS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:20:39',
                'updated_at' => '2020-11-14 11:20:39',
            ),
            4 => 
            array (
                'id' => 35,
                'branch_id' => 1,
                'category_code' => 'A',
                'category_name' => 'AMC',
                'parent_id' => 0,
                'description' => 'AMC LAMPS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-10-27 17:10:08',
                'updated_at' => '2020-11-14 11:19:36',
            ),
            5 => 
            array (
                'id' => 36,
                'branch_id' => 1,
                'category_code' => 'T08',
                'category_name' => 'TOYOTA OIL FILTER',
                'parent_id' => 37,
                'description' => 'TOYOTA OIL FILTER',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-10-27 17:10:59',
                'updated_at' => '2020-11-14 11:23:14',
            ),
            6 => 
            array (
                'id' => 37,
                'branch_id' => 1,
                'category_code' => 'T',
                'category_name' => 'TOYOTA',
                'parent_id' => 0,
                'description' => '',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-10-27 17:14:52',
                'updated_at' => '2020-10-27 17:14:52',
            ),
            7 => 
            array (
                'id' => 38,
                'branch_id' => 1,
                'category_code' => 'T01',
                'category_name' => 'TOYOTA MOUNTS',
                'parent_id' => 37,
                'description' => 'TOYOTA MOUNTS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-10-27 17:15:25',
                'updated_at' => '2020-12-14 15:24:42',
            ),
            8 => 
            array (
                'id' => 43,
                'branch_id' => 1,
                'category_code' => 'Z10',
                'category_name' => 'ISUZU AIR FILTERS',
                'parent_id' => 42,
                'description' => 'ISUZU AIR FILTERS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:25:50',
                'updated_at' => '2020-11-14 11:25:50',
            ),
            9 => 
            array (
                'id' => 44,
                'branch_id' => 1,
                'category_code' => 'Z11',
                'category_name' => 'OIL SEAL',
                'parent_id' => 42,
                'description' => 'ISUZU OIL SEAL',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:26:53',
                'updated_at' => '2020-11-14 11:26:53',
            ),
            10 => 
            array (
                'id' => 45,
                'branch_id' => 1,
                'category_code' => 'U',
                'category_name' => 'LUMIYO',
                'parent_id' => 0,
                'description' => 'LUMIYO BODY PARTS & LIGHTS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:27:23',
                'updated_at' => '2020-11-14 12:08:54',
            ),
            11 => 
            array (
                'id' => 46,
                'branch_id' => 1,
                'category_code' => 'U01',
                'category_name' => 'LUMIYO HEAD LAMPS',
                'parent_id' => 45,
                'description' => 'LUMIYO HEAD LAMPS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:27:51',
                'updated_at' => '2020-11-14 12:08:41',
            ),
            12 => 
            array (
                'id' => 47,
                'branch_id' => 1,
                'category_code' => 'U03',
                'category_name' => 'LUMIYO REAR LAMPS',
                'parent_id' => 45,
                'description' => 'LUMIYO REAR LAMPS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:28:29',
                'updated_at' => '2020-11-14 12:09:06',
            ),
            13 => 
            array (
                'id' => 48,
                'branch_id' => 1,
                'category_code' => 'U04',
                'category_name' => 'LUMIYO CORNER LAMPS',
                'parent_id' => 45,
                'description' => 'LUMIYO CORNER LAMPS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:29:12',
                'updated_at' => '2020-11-14 12:09:23',
            ),
            14 => 
            array (
                'id' => 49,
                'branch_id' => 1,
                'category_code' => 'U02',
                'category_name' => 'SIGNAL LAMP',
                'parent_id' => 45,
                'description' => 'LUMIYO SIGNAL LAMPS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:35:24',
                'updated_at' => '2020-11-14 11:46:10',
            ),
            15 => 
            array (
                'id' => 50,
                'branch_id' => 1,
                'category_code' => 'S',
                'category_name' => 'NEWSTAR',
                'parent_id' => 0,
                'description' => 'NEWSTAR ELECTRICAL ACCS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:38:16',
                'updated_at' => '2020-11-14 11:38:16',
            ),
            16 => 
            array (
                'id' => 51,
                'branch_id' => 1,
                'category_code' => 'S01',
                'category_name' => 'newstar HOLDER',
                'parent_id' => 50,
                'description' => 'NEWSTAR HOLDER',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:38:54',
                'updated_at' => '2020-12-21 13:52:24',
            ),
            17 => 
            array (
                'id' => 52,
                'branch_id' => 1,
                'category_code' => 'S010',
                'category_name' => 'NEWSTAR SWITCH',
                'parent_id' => 50,
                'description' => 'NEWSTAR SWITCH',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:39:57',
                'updated_at' => '2020-11-14 11:39:57',
            ),
            18 => 
            array (
                'id' => 53,
                'branch_id' => 1,
                'category_code' => 'S11',
                'category_name' => 'NEWSTAR SWITCH2',
                'parent_id' => 50,
                'description' => 'NEWSTAR SWITCH2',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:40:24',
                'updated_at' => '2020-12-18 11:41:25',
            ),
            19 => 
            array (
                'id' => 54,
                'branch_id' => 1,
                'category_code' => 'S14',
                'category_name' => 'NEWSTAR TERMINALS',
                'parent_id' => 50,
                'description' => 'NEWSTAR TERMINALS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:41:25',
                'updated_at' => '2020-11-14 11:41:25',
            ),
            20 => 
            array (
                'id' => 55,
                'branch_id' => 1,
                'category_code' => 'S15',
                'category_name' => 'NEWSTAR RELAYS',
                'parent_id' => 50,
                'description' => 'NEWSTAR RELAYS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:42:21',
                'updated_at' => '2020-11-14 11:42:21',
            ),
            21 => 
            array (
                'id' => 56,
                'branch_id' => 1,
                'category_code' => 'C',
                'category_name' => 'COMMON',
                'parent_id' => 0,
                'description' => 'COMMON ITEMS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:43:03',
                'updated_at' => '2020-11-14 11:43:03',
            ),
            22 => 
            array (
                'id' => 57,
                'branch_id' => 1,
                'category_code' => 'C01',
                'category_name' => 'TAPE',
                'parent_id' => 56,
                'description' => 'ADHESIVE TAPE',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:43:54',
                'updated_at' => '2020-11-14 11:45:48',
            ),
            23 => 
            array (
                'id' => 58,
                'branch_id' => 1,
                'category_code' => 'C02',
                'category_name' => 'S/W/C',
                'parent_id' => 56,
                'description' => 'STEERING WHEEL COVER',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:44:19',
                'updated_at' => '2020-11-14 11:45:22',
            ),
            24 => 
            array (
                'id' => 59,
                'branch_id' => 1,
                'category_code' => 'C15',
                'category_name' => 'MUD FLAP',
                'parent_id' => 56,
                'description' => 'MUDFLAP',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:46:48',
                'updated_at' => '2020-11-14 11:46:48',
            ),
            25 => 
            array (
                'id' => 60,
                'branch_id' => 1,
                'category_code' => 'L',
                'category_name' => 'BULBS',
                'parent_id' => 0,
                'description' => 'BULBS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:47:25',
                'updated_at' => '2020-11-14 11:47:25',
            ),
            26 => 
            array (
                'id' => 61,
                'branch_id' => 1,
                'category_code' => 'L01',
                'category_name' => 'LED BULBS',
                'parent_id' => 60,
                'description' => 'LED BULBS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:47:52',
                'updated_at' => '2020-11-14 11:48:56',
            ),
            27 => 
            array (
                'id' => 62,
                'branch_id' => 1,
                'category_code' => 'L02',
                'category_name' => 'NORMAL BULB',
                'parent_id' => 60,
                'description' => 'NORMAL BULB',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:48:24',
                'updated_at' => '2020-11-14 11:49:18',
            ),
            28 => 
            array (
                'id' => 63,
                'branch_id' => 1,
                'category_code' => 'L03',
                'category_name' => 'HALOGEN BULB',
                'parent_id' => 60,
                'description' => 'HALOGEN BULBS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:49:49',
                'updated_at' => '2020-11-14 12:11:37',
            ),
            29 => 
            array (
                'id' => 64,
                'branch_id' => 1,
                'category_code' => 'E',
                'category_name' => 'ELECTRICAL ',
                'parent_id' => 0,
                'description' => 'ELECTRICAL ACCS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:50:29',
                'updated_at' => '2020-11-14 11:50:29',
            ),
            30 => 
            array (
                'id' => 65,
                'branch_id' => 1,
                'category_code' => 'E01',
                'category_name' => 'HOLDERS',
                'parent_id' => 64,
                'description' => 'HOLDERS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:51:19',
                'updated_at' => '2020-11-14 11:51:19',
            ),
            31 => 
            array (
                'id' => 66,
                'branch_id' => 1,
                'category_code' => 'E02',
                'category_name' => 'RELAYS',
                'parent_id' => 64,
                'description' => 'RELAYS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:51:46',
                'updated_at' => '2020-11-14 11:51:46',
            ),
            32 => 
            array (
                'id' => 67,
                'branch_id' => 1,
                'category_code' => 'E03',
                'category_name' => 'SWITCHES',
                'parent_id' => 64,
                'description' => 'SWITCHES',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:52:17',
                'updated_at' => '2020-11-14 11:52:17',
            ),
            33 => 
            array (
                'id' => 68,
                'branch_id' => 1,
                'category_code' => 'E06',
                'category_name' => 'FLASHER',
                'parent_id' => 64,
                'description' => 'FLASHER',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:52:39',
                'updated_at' => '2020-11-14 12:12:15',
            ),
            34 => 
            array (
                'id' => 69,
                'branch_id' => 1,
                'category_code' => 'E09',
                'category_name' => 'POWER CONV',
                'parent_id' => 64,
                'description' => 'POWER CONVERTERS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:53:09',
                'updated_at' => '2020-11-14 11:53:09',
            ),
            35 => 
            array (
                'id' => 70,
                'branch_id' => 1,
                'category_code' => 'E04',
                'category_name' => 'W/SLEEVES',
                'parent_id' => 64,
                'description' => 'WIRE SLEEVES',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:54:09',
                'updated_at' => '2020-11-14 11:54:09',
            ),
            36 => 
            array (
                'id' => 71,
                'branch_id' => 1,
                'category_code' => 'E05',
                'category_name' => 'TERMINALS',
                'parent_id' => 64,
                'description' => 'TERMINALS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:54:29',
                'updated_at' => '2020-11-14 11:54:29',
            ),
            37 => 
            array (
                'id' => 72,
                'branch_id' => 1,
                'category_code' => 'B',
                'category_name' => 'INDIAN',
                'parent_id' => 0,
                'description' => 'INDIAN AUTO PARTS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:54:59',
                'updated_at' => '2020-11-14 11:54:59',
            ),
            38 => 
            array (
                'id' => 73,
                'branch_id' => 1,
                'category_code' => 'B01',
                'category_name' => 'RECTIFIER/IND',
                'parent_id' => 72,
                'description' => 'RECTIFIER',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:55:41',
                'updated_at' => '2020-11-14 11:59:45',
            ),
            39 => 
            array (
                'id' => 74,
                'branch_id' => 1,
                'category_code' => 'B02',
                'category_name' => 'REGULATOR/IND',
                'parent_id' => 72,
                'description' => 'REGULATOR ',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:57:02',
                'updated_at' => '2020-11-14 11:59:58',
            ),
            40 => 
            array (
                'id' => 75,
                'branch_id' => 1,
                'category_code' => 'B03',
                'category_name' => 'DRIVE/M-CLUTCH/IND',
                'parent_id' => 72,
                'description' => 'DRIVE / MOTOR CLUTCH',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:57:36',
                'updated_at' => '2020-11-14 12:00:14',
            ),
            41 => 
            array (
                'id' => 76,
                'branch_id' => 1,
                'category_code' => 'B04',
                'category_name' => 'ARMATURE/IND',
                'parent_id' => 72,
                'description' => 'ARMATURE',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 11:58:00',
                'updated_at' => '2020-11-14 12:00:36',
            ),
            42 => 
            array (
                'id' => 77,
                'branch_id' => 1,
                'category_code' => 'B13',
                'category_name' => 'CABLES/IND',
                'parent_id' => 72,
                'description' => 'CABLES',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 12:04:18',
                'updated_at' => '2020-11-14 12:06:00',
            ),
            43 => 
            array (
                'id' => 78,
                'branch_id' => 1,
                'category_code' => 'T02',
                'category_name' => 'TOYOTA FILTERHEADS',
                'parent_id' => 37,
                'description' => 'FILTER HEADS',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 12:07:59',
                'updated_at' => '2020-11-14 12:07:59',
            ),
            44 => 
            array (
                'id' => 79,
                'branch_id' => 1,
                'category_code' => 'P01001',
                'category_name' => 'CASP',
                'parent_id' => 0,
                'description' => 'CASP LAMP',
                'show_in_invoice' => '1',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-15 08:14:47',
                'updated_at' => '2020-12-18 11:41:44',
            ),
        ));
        
        
    }
}