<?php

use Illuminate\Database\Seeder;

class ProductTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('product')->delete();
        
        \DB::table('product')->insert(array (
            0 => 
            array (
                'id' => 99,
                'stock_id' => 'B13002',
                'branch_id' => 1,
                'item_code' => '1762C',
                'type' => 'stock',
                'category_id' => 77,
                'manufacture_id' => 6,
                'description' => 'SUPER ACE ACCELERATOR CABLES',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 500,
                'reorder_qty' => 50,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 1.0,
                'price' => 1100.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-12-02 13:35:57',
                'updated_at' => '2020-12-02 13:37:03',
            ),
            1 => 
            array (
                'id' => 98,
                'stock_id' => 'C15002',
                'branch_id' => 1,
            'item_code' => 'PS-333(002)',
                'type' => 'stock',
                'category_id' => 59,
                'manufacture_id' => 6,
                'description' => '2PCS SET MUD FLAP',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 490,
                'reorder_qty' => 1,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 465.0,
                'price' => 0.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-12-02 13:13:32',
                'updated_at' => '2020-12-18 14:44:26',
            ),
            2 => 
            array (
                'id' => 97,
                'stock_id' => 'B13001',
                'branch_id' => 1,
                'item_code' => '1522',
                'type' => 'stock',
                'category_id' => 77,
                'manufacture_id' => 6,
                'description' => 'ALTO ACCELERATOR CABLE',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 99,
                'reorder_qty' => 50,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 1.0,
                'price' => 390.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-21 08:28:15',
                'updated_at' => '2020-12-18 14:23:44',
            ),
            3 => 
            array (
                'id' => 96,
                'stock_id' => 'E01001',
                'branch_id' => 1,
                'item_code' => 'HD-2P',
                'type' => 'stock',
                'category_id' => 65,
                'manufacture_id' => 6,
                'description' => '2PIN ALTERNATOR WIRE SOCKET 
',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 500,
                'reorder_qty' => 200,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 0.0,
                'price' => 135.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-20 09:18:22',
                'updated_at' => '2020-11-20 09:18:22',
            ),
            4 => 
            array (
                'id' => 95,
                'stock_id' => 'L03001',
                'branch_id' => 1,
                'item_code' => 'H3_12',
                'type' => 'stock',
                'category_id' => 61,
                'manufacture_id' => 6,
                'description' => 'FOG LIGHT BULB 70W WITH WIRE 12V
',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 1000,
                'reorder_qty' => 500,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 0.0,
                'price' => 75.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-20 09:06:11',
                'updated_at' => '2020-11-20 09:06:11',
            ),
            5 => 
            array (
                'id' => 94,
                'stock_id' => 'L02001',
                'branch_id' => 1,
                'item_code' => '1141',
                'type' => 'stock',
                'category_id' => 61,
                'manufacture_id' => 6,
                'description' => '21W SINGLE FILEMENT BULB 12V AUTO BLUBS
',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 500,
                'reorder_qty' => 200,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 0.0,
                'price' => 25.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-20 09:05:10',
                'updated_at' => '2020-11-20 09:05:10',
            ),
            6 => 
            array (
                'id' => 93,
                'stock_id' => 'L01001',
                'branch_id' => 1,
                'item_code' => '3723 _W_8S_12',
                'type' => 'stock',
                'category_id' => 61,
                'manufacture_id' => 6,
                'description' => 'T10 CAPLESS 8SMD WHITE 12V LED BULB
',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 100,
                'reorder_qty' => 50,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 0.0,
                'price' => 36.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-20 08:11:30',
                'updated_at' => '2020-11-20 08:19:27',
            ),
            7 => 
            array (
                'id' => 92,
                'stock_id' => 'C15001',
                'branch_id' => 1,
                'item_code' => 'PS-334',
                'type' => 'stock',
                'category_id' => 59,
                'manufacture_id' => 6,
            'description' => 'MUD FLAP 4PCS SET (S) 
',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 0,
                'reorder_qty' => 10,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 0.0,
                'price' => 720.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-18 14:41:36',
                'updated_at' => '2020-12-21 13:47:43',
            ),
            8 => 
            array (
                'id' => 91,
                'stock_id' => 'S15001',
                'branch_id' => 1,
                'item_code' => 'RL-211A',
                'type' => 'stock',
                'category_id' => 55,
                'manufacture_id' => 6,
                'description' => 'RELAY 12V. 30A.
',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 0,
                'reorder_qty' => 1,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 0.0,
                'price' => 355.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-18 14:39:29',
                'updated_at' => '2020-11-18 14:39:29',
            ),
            9 => 
            array (
                'id' => 90,
                'stock_id' => 'S14001',
                'branch_id' => 1,
                'item_code' => 'TN-12',
                'type' => 'stock',
                'category_id' => 54,
                'manufacture_id' => 6,
                'description' => 'HORN CLIP-FEMALE
',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 2000,
                'reorder_qty' => 500,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 0.0,
                'price' => 3.95,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-18 14:25:06',
                'updated_at' => '2020-11-18 14:25:06',
            ),
            10 => 
            array (
                'id' => 89,
                'stock_id' => 'S11001',
                'branch_id' => 1,
                'item_code' => 'SW-27',
                'type' => 'stock',
                'category_id' => 53,
                'manufacture_id' => 6,
                'description' => 'POWER SHUTTER SWITCH
',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 350,
                'reorder_qty' => 200,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 0.0,
                'price' => 480.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-18 14:21:49',
                'updated_at' => '2020-11-18 14:21:49',
            ),
            11 => 
            array (
                'id' => 88,
                'stock_id' => 'S10001',
                'branch_id' => 1,
                'item_code' => 'SW-14NA',
                'type' => 'stock',
                'category_id' => 53,
                'manufacture_id' => 6,
                'description' => 'DASH BOARD SWITCH
',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 80,
                'reorder_qty' => 50,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 0.0,
                'price' => 365.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-18 14:19:28',
                'updated_at' => '2020-12-14 11:37:45',
            ),
            12 => 
            array (
                'id' => 87,
                'stock_id' => 'S01001',
                'branch_id' => 1,
                'item_code' => 'LS-14',
                'type' => 'stock',
                'category_id' => 52,
                'manufacture_id' => 6,
                'description' => 'HEADLAMP HOLDER NORMAL
',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 250,
                'reorder_qty' => 50,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 0.0,
                'price' => 145.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-18 14:16:15',
                'updated_at' => '2020-11-20 08:32:39',
            ),
            13 => 
            array (
                'id' => 86,
                'stock_id' => 'U04001',
                'branch_id' => 1,
                'item_code' => '212-1587-A-LH',
                'type' => 'stock',
                'category_id' => 48,
                'manufacture_id' => 6,
                'description' => 'TOYOTA GRAND CABIN-LH
',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 300,
                'reorder_qty' => 150,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 0.0,
                'price' => 1400.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-18 13:57:56',
                'updated_at' => '2020-11-18 13:57:56',
            ),
            14 => 
            array (
                'id' => 85,
                'stock_id' => 'U03001',
                'branch_id' => 1,
                'item_code' => '212-1916-LH',
                'type' => 'stock',
                'category_id' => 47,
                'manufacture_id' => 6,
                'description' => 'TOYOTA HIACE LH-50-LH
',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 1000,
                'reorder_qty' => 200,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 1.0,
                'price' => 880.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-18 13:56:05',
                'updated_at' => '2020-11-21 08:22:11',
            ),
            15 => 
            array (
                'id' => 84,
                'stock_id' => 'U02001',
                'branch_id' => 1,
                'item_code' => '212-1678-LH',
                'type' => 'stock',
                'category_id' => 48,
                'manufacture_id' => 6,
                'description' => 'TOYOTA HIACE LH-113/NEW FACE-LH
',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 49,
                'reorder_qty' => 20,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 0.0,
                'price' => 890.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-18 13:50:02',
                'updated_at' => '2020-12-18 14:23:44',
            ),
            16 => 
            array (
                'id' => 83,
                'stock_id' => 'U01001',
                'branch_id' => 1,
                'item_code' => '212-1157-LH',
                'type' => 'stock',
                'category_id' => 46,
                'manufacture_id' => 6,
                'description' => 'GRAND CABIN-LH
',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 10,
                'reorder_qty' => 5,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 0.0,
                'price' => 2945.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-18 13:47:26',
                'updated_at' => '2020-11-18 13:47:26',
            ),
            17 => 
            array (
                'id' => 82,
                'stock_id' => 'T02002',
                'branch_id' => 1,
                'item_code' => '23301-54410',
                'type' => 'stock',
                'category_id' => 78,
                'manufacture_id' => 6,
                'description' => 'TOYOTA',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 100,
                'reorder_qty' => 50,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 0.0,
                'price' => 1355.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-18 13:43:26',
                'updated_at' => '2020-11-18 13:43:27',
            ),
            18 => 
            array (
                'id' => 81,
                'stock_id' => 'T09001',
                'branch_id' => 1,
                'item_code' => '23303-64010',
                'type' => 'stock',
                'category_id' => 41,
                'manufacture_id' => 6,
                'description' => 'KAFC-158
',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 500,
                'reorder_qty' => 150,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 0.0,
                'price' => 690.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-18 13:40:53',
                'updated_at' => '2020-11-18 13:40:53',
            ),
            19 => 
            array (
                'id' => 80,
                'stock_id' => 'T01001',
                'branch_id' => 1,
                'item_code' => '37230-35050',
                'type' => 'stock',
                'category_id' => 38,
                'manufacture_id' => 6,
                'description' => 'PICKUP LN50/ LN 60
',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 500,
                'reorder_qty' => 50,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 0.0,
                'price' => 690.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-18 13:06:53',
                'updated_at' => '2020-11-18 13:09:00',
            ),
            20 => 
            array (
                'id' => 79,
                'stock_id' => 'T08001',
                'branch_id' => 1,
                'item_code' => '90915-10003',
                'type' => 'stock',
                'category_id' => 36,
                'manufacture_id' => 6,
                'description' => 'KAC-110',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 995,
                'reorder_qty' => 100,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 1.0,
                'price' => 320.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-18 13:04:07',
                'updated_at' => '2020-12-18 14:23:44',
            ),
            21 => 
            array (
                'id' => 78,
                'stock_id' => 'A02001',
                'branch_id' => 1,
                'item_code' => 'GE-002',
                'type' => 'stock',
                'category_id' => 40,
                'manufacture_id' => 6,
                'description' => 'AMC - HOOD LAMP
',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 200,
                'reorder_qty' => 50,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 0.0,
                'price' => 480.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-18 12:53:16',
                'updated_at' => '2020-11-18 12:53:16',
            ),
            22 => 
            array (
                'id' => 77,
                'stock_id' => 'Z11001',
                'branch_id' => 1,
                'item_code' => '8-94248-117-1',
                'type' => 'stock',
                'category_id' => 44,
                'manufacture_id' => 6,
            'description' => 'FRONT NPR OIL SEAL (70X90X7.5)
',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 0,
                'reorder_qty' => 1,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 0.0,
                'price' => 500.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-18 12:36:27',
                'updated_at' => '2020-11-18 12:36:27',
            ),
            23 => 
            array (
                'id' => 76,
                'stock_id' => 'C02009',
                'branch_id' => 1,
                'item_code' => 'BL-L',
                'type' => 'stock',
                'category_id' => 58,
                'manufacture_id' => 6,
            'description' => 'BLACK_(L)
',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 200,
                'reorder_qty' => 1,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 0.0,
                'price' => 710.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-18 12:27:49',
                'updated_at' => '2020-11-18 12:27:49',
            ),
            24 => 
            array (
                'id' => 75,
                'stock_id' => 'C01001',
                'branch_id' => 1,
            'item_code' => '3M-FDB (L)',
                'type' => 'stock',
                'category_id' => 57,
                'manufacture_id' => 6,
                'description' => '3M_DOUBLE SIDE  FOAM TAPE_10M
',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 201,
                'reorder_qty' => 1,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 0.0,
                'price' => 1280.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-18 12:14:46',
                'updated_at' => '2020-12-18 14:58:02',
            ),
            25 => 
            array (
                'id' => 74,
                'stock_id' => 'Z10001',
                'branch_id' => 1,
                'item_code' => '5-14218-015-0',
                'type' => 'stock',
                'category_id' => 43,
                'manufacture_id' => 6,
                'description' => 'KA-509',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 0,
                'reorder_qty' => 1,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 0.0,
                'price' => 980.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-16 10:49:35',
                'updated_at' => '2020-11-16 10:50:23',
            ),
            26 => 
            array (
                'id' => 73,
                'stock_id' => 'A01001',
                'branch_id' => 1,
                'item_code' => 'ISU020-L',
                'type' => 'stock',
                'category_id' => 39,
                'manufacture_id' => 6,
            'description' => 'AMC REAR LAMP (LH)',
                'default_store_location' => NULL,
                'kg' => NULL,
                'store_location' => NULL,
                'barcode' => '',
                'reorder_point' => 0,
                'qty_on_hand' => 101,
                'reorder_qty' => 10,
                'length' => '',
                'width' => '',
                'height' => '',
                'weight' => '',
                'rent_per_day' => NULL,
                'rent_per_week' => NULL,
                'rent_per_month' => NULL,
                'cost' => 0.0,
                'price' => 1165.0,
                'status' => 'A',
                'created_by' => 9,
                'updated_by' => 9,
                'deleted_at' => NULL,
                'created_at' => '2020-11-14 12:33:18',
                'updated_at' => '2020-12-18 14:44:26',
            ),
        ));
        
        
    }
}